- lectures/multivariate_normal.md
fixes https://github.com/QuantEcon/lecture-python.myst/issues/59
> 🐛 FIX: Math syntax issue

- lectures/cass_koopmans_2.md
- lectures/exchangeable.md
- lectures/finite_markov.md
- lectures/harrison_kreps.md
- lectures/lake_model.md
- lectures/likelihood_bayes.md
- lectures/lq_inventories.md
- lectures/lqcontrol.md
- lectures/markov_asset.md
- lectures/navy_captain.md
- lectures/odu.md
- lectures/perm_income.md
- lectures/perm_income_cons.md
- lectures/rational_expectations.md
- lectures/re_with_feedback.md
- lectures/samuelson.md
- lectures/wald_friedman.md
@mmcky did you had something like this PR in mind when you raised this issue https://github.com/QuantEcon/lecture-python.myst/issues/77 ?
> update sources lecture-python (9ae923d) using tomyst (b06cacb)

- lectures/ifp.md
fixes #25 
The link was split across two lines
> [ifp] fix broken link

- lectures/wald_friedman.md
> [wald_friedman] adjust blockquote syntax for multiline math

- lectures/RCE_tom_v13.md
- lectures/_toc.yml
This Lecture is on `arrow` securities
> [New Lecture] new lecture on fun things

- .github/workflows/publish.yml
This enables the `CNAME` file for custom domain
> enable CNAME creation for custom domain

- environment.yml
> Update "quantecon-book-theme" 

- environment.yml
This adds stability to the `quantecon-book-theme`
> MAINT: pin quantecon-book-theme to 0.1.7

- .github/workflows/execution.yml
- lectures/navy_captain.md
This PR enables execution checking on `windows, linux, and macos` on a `daily` schedule
> [GA] enable execution checks for windows, linux, os x

- .github/workflows/cache.yml
- .github/workflows/ci.yml
- .github/workflows/publish.yml
This PR enables fetching cache assets from cache.yml workflow
> MAINT: Enable cache using cache.yml workflow

- lectures/short_path.md
Remove redundant array creation.
> [short_path] Delete next_J in compute_cost_to_go

- lectures/career.md
The current code happens to works, because `greedy_star` refers to that in the global scope.
> [career] Correct variable in gen_path

- environment.yml
This PR upgrades to `jupyter-book==0.11.12`
> MAINT: Update to jupyter-book==0.11.2

- lectures/career.md
`qe.random.draw` returns an `int`.
> [career] Remove int()

- lectures/two_auctions.md
Hi @thomassargent30 and @mmcky , these are typos @natashawatkins picked up in the first auction lecture.
> Fixed minor typos in Auction lecture

- lectures/two_auctions.md
- Thanks to Andrey for pointing this out
> Correct some typos in two_auctions.md

- lectures/back_prop.md
> FIX: update for compatibility for jax>=0.3.2

- .github/workflows/ci.yml
This PR adjust `ci` workflow  settings to fix issue with preview showing on #195
> GA: add pull_reqest to ci workflow to trigger on fork contributions

- .github/workflows/cache.yml
- .github/workflows/ci.yml
- .github/workflows/execution.yml
- .github/workflows/publish.yml
- environment.yml
This updates the `quantecon` environment from `.github`
> MAINT: Update quantecon environment

- .github/workflows/publish.yml
This PR re-enables PDF publishing
> Enable PDF for publishing workflow

- lectures/lln_clt.md
> Updated LLN lecture -- small improvement

- lectures/mccall_fitted_vfi.md
Hi @jstac , this PR fixes issue #246 while keeping the results from the remaining code cells the same for lecture ``mccall_fitted_vfi``.
> [mccall_fitted_vfi] fix issue #246

- lectures/_config.yml
ordering taken from this PR https://github.com/executablebooks/MyST-NB/pull/305
fixes https://github.com/QuantEcon/lecture-python.myst/issues/95
> ENH: Ordering latex build render priorities in _config

- lectures/_static/lecture_specific/coleman_policy_iter/solve_time_iter.py
- lectures/_static/lecture_specific/optgrowth/solve_model.py
- lectures/cake_eating_numerical.md
- lectures/career.md
- lectures/ifp_advanced.md
- lectures/jv.md
- lectures/mccall_correlated.md
- lectures/mccall_model.md
- lectures/navy_captain.md
- lectures/odu.md
- lectures/wald_friedman.md
Fixes #175 
Fixes #176 
cc @jstac
> Few bug fixes on convergence conditions

- environment.yml
Hi @mmcky,
This is an attempt to resolve #275. It seems that the problem is solved.
Could you have a quick look and merge if it looks good to you?
> FIX: Update arviz to 0.13.0

- .github/workflows/cache.yml
- .github/workflows/ci.yml
- .github/workflows/publish.yml
This PR adds GPU build support for:
> ENH: Setup EC2 based builds GPU support

- lectures/odu.md
> FIX: broken links to section titles

- .github/workflows/ci.yml
- lectures/mix_model.md
> ENH: minor edits of new lecture mix-model

- lectures/prob_matrix.md
> Update the Deprecated `set_matplotlib_formats`

- lectures/finite_markov.md
- lectures/short_path.md
This PR addresses #177 by adding a context manager `with` to the two aforementioned lectures.
> Update context manager

- lectures/mccall_q.md
Fixes #310 
cc @thomassargent30 @jstac
> Fix some issues in McCall Q-learns

- .github/workflows/ci.yml
- lectures/kesten_processes.md
- lectures/wealth_dynamics.md
> Update jax box at top of lecture, update CUDA to 11.8

- .github/workflows/ci.yml
- environment.yml
- lectures/linear_algebra.md
- lectures/lln_clt.md
> ENH: Upgrade docker with anaconda==2023.03

- lectures/inventory_dynamics.md
Hi @jstac,
This small PR fixes a small typo in the Inventory Dynamics lecture I found when doing JAX conversion. Please merge if it looks good to you.
Many thanks in advance.
> [Inventory Dynamics] Fix A Small Typo in Text

- lectures/wealth_dynamics.md
Reverts #304 
https://github.com/QuantEcon/lecture-jax/pull/22
> Remove JAX from Wealth dynamics

- lectures/mccall_model.md
- lectures/mle.md
- lectures/var_dmd.md
> Simplify basic McCall model

- lectures/_config.yml
Simply changes the analytics code in the config file to the updated version 4 code.
> Migrating to Google Analytics 4 with new code

- lectures/newton_method.md
Hi @mmcky, this should do the job of reverting the JAX content that is merged into the previous branch.
Many thanks.
> Revert a Merge in `revert-newton`

- lectures/_static/lecture_specific/optgrowth_fast/ogm.py
- lectures/_static/lecture_specific/optgrowth_fast/ogm_crra.py
- lectures/aiyagari.md
- lectures/coleman_policy_iter.md
- lectures/egm_policy_iter.md
- lectures/geom_series.md
- lectures/hoist_failure.md
- lectures/house_auction.md
- lectures/ifp.md
- lectures/ifp_advanced.md
- lectures/imp_sample.md
- lectures/jv.md
- lectures/kalman.md
- lectures/kesten_processes.md
- lectures/linear_algebra.md
- lectures/lln_clt.md
- lectures/mccall_fitted_vfi.md
- lectures/mccall_q.md
- lectures/mle.md
- lectures/multi_hyper.md
- lectures/opt_transport.md
- lectures/optgrowth_fast.md
- lectures/svd_intro.md
- lectures/two_auctions.md
- lectures/uncertainty_traps.md
- lectures/util_rand_resp.md
- lectures/von_neumann_model.md
> Remove unused imports

- .github/workflows/cache.yml
- .github/workflows/ci.yml
- .github/workflows/execution.yml
- .github/workflows/linkcheck.yml
- .github/workflows/publish.yml
- environment.yml
- lectures/cass_koopmans_2.md
This PR upgrades to:
- anaconda==2023.09
- python=3.11
- quantecon-book-theme==0.6.0
> MAINT: Upgrade software stack

- lectures/_toc.yml
- lectures/kalman_2.md
- lectures/perm_income.md
Hi @kp992,
Many thanks for the discussions in the email thread. I have created this draft PR to work on this lecture. We can invite Tom once we finalize the code part.
Best,
Humphrey
> Draft Lecture on Second Look at the Kalman filter

- lectures/ols.md
- lectures/pandas_panel.md
> Fix matplotlib warnings

- .github/workflows/ci.yml
- lectures/_config.yml
This PR tests infrastructure for linking old lectures to the new reorg structure
fixes #351
> TST: test sphinx-reredirect

- lectures/_config.yml
This PR adjust the bibliography style to use `author_year`
> ENH: update to author_year bibtex style

- lectures/harrison_kreps.md
> FIX: markdown table formatting

- README.md
This PR addresses https://github.com/QuantEcon/meta/issues/132
> MAINT: standardize README

- .github/workflows/ci.yml
- environment.yml
This PR updates to the latest `anaconda` release
> ENH: update anaconda==2024.06

- .github/workflows/cache.yml
- .github/workflows/ci.yml
- .github/workflows/execution.yml
- .github/workflows/linkcheck.yml
- .github/workflows/publish.yml
- environment.yml
> MAINT: update docker backend

- .github/workflows/ci.yml
- lectures/odu.md
This PR reformats a wide equation in the ODU lecture
> [odu] FIX: reformat wide equation

- .github/workflows/cache.yml
This PR fixes the build cache issues for GitHub Actions
> FIX: jupyter cache

- .github/workflows/cache.yml
- .github/workflows/ci.yml
- .github/workflows/collab.yml
- .github/workflows/publish.yml
This PR enables testing for execution compatibility with `google colab`
> ENH: enable google collab compat testing

- .github/workflows/cache.yml
This PR changes the build cache to execute weekly at 3am on Monday.
> MAINT: schedule cache builds for 3am on Monday (weekly)

- lectures/mle.md
> [mle] Update the String Format

- lectures/odu.md
This PR fixes syntax warnings due to `python=3.12+`
> FIX: syntax warning

- lectures/_static/quant-econ.bib
- lectures/cass_fiscal.md
This PR includes updates by @thomassargent30 and @HumphreyYang
> [cass_koopman] Updates to lecture

- lectures/_toc.yml
- lectures/prob_matrix.md
- lectures/stats_examples.md
This PR includes Tom's edits to the lecture `prob_matrix`.
> [prob_matrix] Restructure and splitting

- lectures/mccall_q.md
Replace np.sum(a * b) with a @ b
https://github.com/QuantEcon/lecture-python.myst/issues/463
> Replace np.sum(a * b) with a @ b in lecture-python.myst.mccall_q.md

- .github/workflows/collab.yml
- lectures/egm_policy_iter.md
> FIX: links update

- .github/workflows/linkcheck.yml
This PR accepts html code `200` and runs weekly instead of daily.
> FIX: update linkchecker

- lectures/_toc.yml
- lectures/ak_aiyagari.md
This PR adds a lecture on a heterogeneous agent OLG model with transition dynamics written by @thomassargent30 and @shizejin
> [ak_aiyagari] New lecture on heterogeneous agent OLG model with transition dynamics

- lectures/aiyagari.md
This PR updates the lecture on Aiyagari models with JAX and checks for stylesheet compliance.
> [aiyagari] Update lecture with JAX and check for stylesheet compliance
