QuantEcon/lecture-python.myst

lectures/exchangeable.md, lectures/lq_inventories.md, lectures/multivariate_normal.md
`begin{align}`, `begin{equation}`, `begin{split}` is unnecessary inside $$ math environment, and breaks latex builds.
=> Math code fixes making it compatible for latex

.github/workflows/ci.yml, .github/workflows/publish.yml, .gitignore
This PR fixes #12 by using `build` artifacts from the `publish.yml` process. 
Not going to implement the second as it is more risky given it is on the `publishing` pathway. We can add this at a later date.
=> ENH: enable cached build folders using artifacts

lectures/_config.yml
This PR fixes #38 by promoting `latex` as a preferred output type for rendering by `mathjax`
=> Update Rendering Priorities to promote LaTeX outputs

lectures/harrison_kreps.md
fixes #29 
This PR manually fixes the tables in `harrison_kreps` lecture due to https://github.com/executablebooks/sphinx-tomyst/issues/90
=> [harrison_kreps] Fix tables

lectures/optgrowth_fast.md
fixes #25 
the `role` was split across two lines.
=> [optgrowth_fast] fix broken links

.github/workflows/publish.yml, _notebook_repo/README.md, environment.yml
=> [download notebooks] Updates to support Download Notebooks

lectures/aiyagari.md, lectures/linear_algebra.md, lectures/linear_models.md, lectures/mle.md
As discussed with @mmcky , I create this PR to fix issue #57 by removing the ``only`` directives with unified markdown syntax in the following lectures:
- [aiyagari](https://github.com/QuantEcon/lecture-python.myst/blob/main/lectures/aiyagari.md),
- [linear_algebra](https://github.com/QuantEcon/lecture-python.myst/blob/main/lectures/linear_algebra.md),
- [linear_models](https://github.com/QuantEcon/lecture-python.myst/blob/main/lectures/linear_models.md),
- [mle](https://github.com/QuantEcon/lecture-python.myst/blob/main/lectures/mle.md)
=> Remove only html and latex directives for common markdown source

lectures/_static/quant-econ.bib, lectures/markov_asset.md
This PR migrates changes made in `lecture-python` 
https://github.com/QuantEcon/lecture-python/commit/5623ec636260e1eb6ae6930e6eff146eea8a725a
=> MIGRATE: [markov_asset] migrate lecture-source (5623ec6) with manual adjustment

lectures/harrison_kreps.md
This PR migrates the recent changes made to `harrison_kreps.rst`
https://github.com/QuantEcon/lecture-python/commit/32574c3ef1bb7d234242c2af0d889a89f104c262
https://github.com/QuantEcon/lecture-python/commit/c1a949e52e4442a83a81040fe92bdaff8e8152de
https://github.com/QuantEcon/lecture-python/commit/00d6de94cc76f973587d2eedae7f1df880cfce8a
=> [harrison_kreps] Migrate updates from lecture-source RST repo

.github/workflows/publish.yml
This PR changes the pathway for publishing to `gh-pages` using a tag based approach to trigger changes to be built for `gh-pages`. To setup an `automated` update to the live site you would need to create a `tag` with the `publish*` pattern such as `publish-2021mar16`
=> PUBLISH: Setup for live publishing based on "publish*" tags

.github/workflows/publish.yml
This PR enables `Github Actions` to sync the latest set of `download notebooks` to `lecture-python.notebooks`
=> [SYNC] enable sync to lecture-python.notebooks repository

lectures/_toc.yml, lectures/status.md
This PR adds a page to publish the `execution` statistics. 
We will work on adding badges to each lecture as an extension.
=> [Execution] publish execution statistics for website

environment.yml
This is a maintenance update to our software environment due to an issue with nbdime -> jupyter_server not updating tornado to a compatible version.
=> FIX: update environment for quantecon

.github/workflows/ci.yml, environment.yml, lectures/linear_models.md, lectures/perm_income_cons.md, lectures/samuelson.md
Modify the code in the lectures related with the recent change in QuantEcon/QuantEcon.py#569
Thanks @shizejin I have migrate this from the `RST` repository. 
If you could review and approve this PR that would be great.
=> Modify the callings of LinearStateSpace.stationary_distributions

environment.yml
`quantecon-book-theme=0.1.7` has now been released on PyPI
=> MAINT: revert back to pip installs using quantecon-book-theme=0.1.7

environment.yml
This PR pins to the current versions of `jupyter-book` software stack for stability in publishing
=> pin environment for upcoming major changes to jupyter-book

environment.yml, lectures/_config.yml
This updates to use the latest `quantecon-book-theme`
=> MAINT: update them to quantecon-book-theme=0.2.1

.github/workflows/ci.yml, .github/workflows/publish.yml, environment.yml, lectures/_config.yml
This PR enables a book style `PDF` via LaTeX support. 
**Note:** It also adds `download notebooks` builds to `CI` to ensure they build prior to `publish` workflow.
=> [pdflatex] Enable book style build of PDF via LaTeX

.github/workflows/ci.yml, environment.yml, lectures/_toc.yml
This PR is adjust the repository for the [upcoming changes to jupyter-book and `sphinx-external-toc`](https://github.com/executablebooks/jupyter-book/pull/1293)
Checks
=> MAINT: Updates for new release of juptyer-book=0.11.1

.github/workflows/cache.yml
=> MAINT: Add separate cache workflow to supply cache assets

lectures/finite_markov.md
Migrated from QuantEcon/lecture-python#381
=> [finite_markov] Modify wording

lectures/finite_markov.md
Migrated from QuantEcon/lecture-python#382
=> [finite_markov] Remove redundant array creation

lectures/short_path.md
`num_nodes`  in the `compute_cost_to_go` function refers to that in the global scope, but it should be defined in the local scope.
=> [short_path] Define num_nodes in compute_to_go

environment.yml
This upgrades `sphinx-tojupyter==0.1.2` which brings in `chapter` context in equation numbers for the download notebooks.
=> ENH: Upgrade sphinx-tojupyer=0.1.2

lectures/short_path.md
Fix the following warning.
```
DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
J = np.zeros_like(nodes, dtype=np.int)
```
=> [short_path] Fix DeprecationWarning

lectures/complex_and_trig.md, lectures/inventory_dynamics.md, lectures/lake_model.md, lectures/markov_asset.md, lectures/multivariate_normal.md, lectures/samuelson.md
Hi @jstac and @oyamad , thanks for your nice comments. This PR fix #165  's remaining patterns, mentioned by @oyamad , except for the following:
- [lake_model](https://python.quantecon.org/lake_model.html): ``V = np.ones(len(mcm.w_vec))``
Do you think we should also change the ``np.ones`` pattern to ``np.full`` in the above lecture?
=> np.ones * alpha -->> np.full

lectures/career.md
The behavior of the current code
```py
cw = CareerWorkerProblem()
v_star = solve_model(cw,verbose=True,max_iter = 500)
```
```
Error at iteration 25 is 1.4599451216938633.
Error at iteration 50 is 0.40497355408797375.
Error at iteration 75 is 0.11233544129407846.
Error at iteration 100 is 0.03116068010700701.
Error at iteration 125 is 0.008643647753075356.
Error at iteration 150 is 0.0023976577604400973.
Error at iteration 175 is 0.0006650852626535197.
Error at iteration 200 is 0.00018448771709245193.
Converged in 212 iterations.
```
```py
v_star = solve_model(cw,verbose=True,max_iter = 212)
```
```
Error at iteration 25 is 1.4599451216938633.
Error at iteration 50 is 0.40497355408797375.
Error at iteration 75 is 0.11233544129407846.
Error at iteration 100 is 0.03116068010700701.
Error at …
```
=> [career] Correct if collections in solve_model

lectures/intro.md
This will remove the sentence from non-html builds.
=> [intro] wrap intro sentence about website into an only directive for html

.github/workflows/cache.yml, .github/workflows/ci.yml, .github/workflows/execution.yml, .github/workflows/publish.yml, lectures/five_preferences.md, path.py
=> FIX: matplotlib builds using LaTeX

lectures/samuelson.md
Closes https://github.com/QuantEcon/lecture-python.myst/issues/207
This PR corrects several minor errors in the simulation when using the `LinearStateSpace` class.
1. the attribute of the `LinearStateSpace` for controlling the initial distribution is `mu_0` instead of `μ_0`
2. to be less confusing, I changed all the attribute names related with `LinearStateSpace` to their names denoted in the [source code](https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/lss.py#L67)
3. when setting the initial distribution to be the stationary distribution, we should use `mu_x` and `Sigma_x` instead of `mu_y` and `Sigma_y`
4. when the "stationary" mode is off, the code still unintentionally simulates data from its stationary distribution, as we were setting `μ_0` at the stationary values. I …
=> Modify `samuelson`

lectures/opt_transport.md
In response to the comment of @alfredgalichon
=> Added column major order note to OT lecture

lectures/opt_transport.md
`opt_transport` was giving the following error on `cache` run:
```
[0;31mTypeError[0m: 'module' object is not callable
TypeError: 'module' object is not callable
```
=> [opt_transport] Update linprog_simplex import

lectures/_static/quant-econ.bib, lectures/rand_resp.md, lectures/util_rand_resp.md
=> FIX: review new lectures for compat with jb html and latex builders

lectures/util_rand_resp.md
This ensures math references are unique in `util_rand_resp`
It would be good to also go through this document and update the links in the text using `jb` links rather than numbers which are currently being used. 
I will merge this to get the new pages live but I have a tracking issue to loop back and do this work
https://github.com/QuantEcon/lecture-python.myst/issues/225
=> [util_rand_resp] Ensure math labels are unique

lectures/util_rand_resp.md
- @mmcky is there a way to cite equations in text? the equation labels in the text didn't match the automatic equation labs. I changed the references but guessed the syntax.
- I think an article stills need citation? "XXXX Ljungqvist"
- I removed the font selection because it was producing an error
=> Edit typos and prettify code in util_rand_resp.rst

lectures/samuelson.md
The string for one of the plots should be formed without any included newlines for mathjax to render `$` properly
=> FIX: Plot rendering in Samuelson Lecture

environment.yml, lectures/ar1_bayes.md, lectures/ar1_turningpts.md, lectures/bayes_nonconj.md, lectures/lagrangian_lqdp.md, lectures/prob_matrix.md
Make some adjustments to fix:
1. headers
2. equation references
3. execution for `ar1_turningpts`
=> FIX: Adjustments for main branch to compile

lectures/prob_matrix.md
* I also changed Jupiter notebook settings to only show up to the 3 decimal places
=> Fix typos and latex errors in prob_matrix.md

lectures/geom_series.md
=> Fix Taylor series about g=0 in Geometric series lecture

lectures/ar1_bayes.md
#252 
cc @jstac @thomassargent30
=> AR1 Bayes Fixes

.github/workflows/linkcheck.yml, lectures/_static/quant-econ.bib, lectures/cass_koopmans_1.md, lectures/lagrangian_lqdp.md, lectures/linear_algebra.md, lectures/mle.md, lectures/ols.md, lectures/opt_transport.md, lectures/rational_expectations.md, lectures/svd_intro.md, lectures/wald_friedman.md
This PR runs a link checker on:
1. schedule (daily),
2. on the creation or reopening of a PR (so only will run once)
=> ENH: Add link checker GitHub Action

lectures/geom_series.md
Hi @jstac , this PR fixes the MatplotlibDeprecationWarning in lecture ``geom_series`` (left: before fixing; right: after fixing):
=> [geom_series] fix MatplotlibDeprecationWarning

lectures/aiyagari.md, lectures/coleman_policy_iter.md, lectures/finite_markov.md, lectures/intro.md, lectures/lake_model.md, lectures/linear_algebra.md, lectures/mle.md, lectures/ols.md, lectures/pandas_panel.md, lectures/status.md, lectures/troubleshooting.md, lectures/two_auctions.md
Hi @mmcky,
This PR fixes #261. 
Could you please merge it if it looks good to you?
Many thanks.
=> FIX: Broken Links and Redirects

lectures/ols.md
Hi @mmcky,
This PR resolves #263. I found the links were updated on the MIT website yesterday. I have now replaced the internet archive links with the links to the new MIT website.
Could you please review this change and merge it if it looks good to you?
Many thanks.
=> Update Acemoglu Links

.github/workflows/ci.yml, lectures/ar1_bayes.md, lectures/career.md, lectures/cass_koopmans_2.md, lectures/heavy_tails.md, lectures/hoist_failure.md, lectures/house_auction.md, lectures/lake_model.md, lectures/lln_clt.md, lectures/mccall_model_with_separation.md, lectures/pandas_panel.md, lectures/prob_matrix.md, lectures/re_with_feedback.md, lectures/short_path.md
Hi @mmcky,
This resolves #266. I also fixed a few deprecations and bugs along the way:
1.  In [hoist_failure.md](https://python.quantecon.org/hoist_failure.html#fault-tree-uncertainties), there are a few deprecation warnings for `np.int()`, which is replaced by `int()`.
2. In [pandas_panel.md](https://python.quantecon.org/pandas_panel.html), `realwage['2015']` raises future warning and changed to `realwage.loc['2015']`, and similarly, `merged.mean(level='Continent', axis=1).head()` is changed to `merged.groupby(level='Continent', axis=1).mean()`
3. [Exercise 2 of Heavy-Tailed Distributions](https://python.quantecon.org/heavy_tails.html#solutions) was not shown and is now fixed.
Could you please review these changes, and merge them if it looks good to you?
Many thanks.
=> Switch to Hint and Note Admonitions

.github/workflows/cache.yml
This PR enables `latex` access during `cache.yml` runs to ensure matplotlib has access to `latex` for rendering latex strings as a subprocess
=> Enable LaTeX availability during cache runs

.github/workflows/cache.yml, .github/workflows/ci.yml, .github/workflows/publish.yml, lectures/mix_model.md
This PR adjusts latex installs to ensure `matplotlib` has all the libraries needed to render latex in figures
Fixes #287
=> MAINT: Revise LaTeX support for containers

lectures/markov_asset.md, lectures/mix_model.md
Migrates #286 to be local (cc: @Smit-create)
=> FIX: Adjust for quantecon==0.6.0

lectures/status.md, lectures/wealth_dynamics.md
=> JAX: Add JAX implementation for wealth dynamics

lectures/kesten_processes.md, lectures/status.md
This PR resolves #299. It is a draft to see the speed comparison on the server.
=> [kesten_processes] Rewrite Main Exercise Using JAX

.github/workflows/ci.yml, .github/workflows/publish.yml
Solves an issue using the most recent release of jax #315
=> MAINT: pin jax==0.4.2 for all workflow

lectures/newton_method.md
Hi @jstac , this PR fix the formulae we discussed last Friday.
Also, I add a tag at
https://github.com/QuantEcon/lecture-python.myst/blob/604d707e132261bc9071bc5f9faf9e1c4e35f670/lectures/newton_method.md?plain=1#L466
for referencing in the Jax lecture.
=> Fix wrong formulae and matrix

.github/workflows/cache.yml, .github/workflows/ci.yml, .github/workflows/publish.yml, environment.yml, lectures/_config.yml
This PR upgrades to `jupyter-book==0.15.1` + associated packages
=> ENH: Upgrade to jb-0.15.1 + associated packages

lectures/lp_intro.md, lectures/opt_transport.md
=> Fix scipy warnings - Optimal transport and LP intro

lectures/mccall_model.md
thanks @HumphreyYang for picking this up in #340 
This PR fixes the PDF build due to an error introduced in `mccall_model` causing some malformed math.
=> FIX: syntax for PDF builds

lectures/scalar_dynam.md
Hi @jstac, this PR fixes #208.
=> Fix Userwarning

lectures/mccall_model_with_separation.md
Use `numpy.searchsorted` (which uses binary search) instead of the linear search in the original content.
=> Improve the computation of the reservation wage

lectures/complex_and_trig.md
=> Fix sympy imports and exercise

lectures/cass_koopmans_1.md
The explantion refers to `constraint2` i.e. derivative wrt `K_t`
=> cass_koopmans_1.md: typo in attribution of explanation

.github/workflows/cache.yml, .github/workflows/ci.yml, .github/workflows/publish.yml, environment.yml, lectures/ar1_bayes.md
=> MAINT: Upgrade docker to -b (sphinx-reredirects, latest theme)

lectures/_config.yml, lectures/intro.md
This PR applies author update as using `quantecon-book-theme==0.7.0`
@HumphreyYang I had to update the author for this series but I don't think that will be an issue for migration as you are using a different _config.yml for the reorg
=> Update author information compat with quantecon-book-theme==0.7.0

lectures/lake_model.md
Compute the steady state by the straightforward formula for a 2x2 Markov chain instead of iteration.
See also: #169.
=> [LakeModel] Simplify computation of the steady state

lectures/svd_intro.md
Corrected some typos. 
Added a brief description explaining why the Eckart-Young theorem is important.
Added details to how the PCA for any given matrix.
Changed the n_components term in the codes to r_components, so it is in accord with the definition of the Eckward-Young theorem and doesn't create confusion with the n columns of the matrix.
Added an exercise and its solution at the end (I've never used Sphinx, so not sure if it's done correctly).
=> Suggestions for the SVD lecture

lectures/svd_intro.md
This PR fixes:
- aligned issue for `LaTeX`
- removes white space
=> FIX: tidy up and fix align issue for LaTeX

lectures/_static/quant-econ.bib, lectures/kalman_2.md, lectures/var_dmd.md
This PR address https://github.com/QuantEcon/meta/issues/134 for this repository
=> MAINT: remove matplotlib inline

lectures/_static/quant-econ.bib
There is a duplicate error issue in `quant-econ.bib` 
This PR addresses this.
=> FIX: remove duplicate entries for bibtex

lectures/cass_koopmans_1.md
The current build cache has expired so waiting on #400
=> ENH: Tom's edits for July

lectures/_static/quant-econ.bib, lectures/_toc.yml, lectures/ak2.md
This PR migrates the `ak2` from `intro` lecture series. 
This [PR ](https://github.com/QuantEcon/lecture-python-intro/pull/508) was not merged prior to migration and should be reviewed when this PR is merged.
=> ENH: migrate ak2 from intro lecture series

.github/dependabot.yml, .github/workflows/cache.yml, .github/workflows/ci.yml, .github/workflows/publish.yml
=> MAINT: migrate to github actions gpu instance, dependabot testing

lectures/bayes_nonconj.md
Use float `dtype` for numpyro backend in `bayes_nonconj`.
Fixes #417
=> Use float dtype for numpyro

.github/workflows/cache.yml, .github/workflows/ci.yml, .github/workflows/publish.yml, environment.yml
=> MAINT: update Jupyter-book to 1.0.3 and associated packages

lectures/status.md
Add check for `GPU` on the status page.
Helps to close issues such as https://github.com/QuantEcon/lecture-python.myst/issues/323 to verify access to GPU.
=> MAINT: add nvidia-smi output to status page

lectures/re_with_feedback.md
This PR fixes strings in the matplotlib context to prevent warnings
fixes #429
=> [re_with_feedback] FIX: matplotlib strings with LaTeX

lectures/re_with_feedback.md
=> [re_with_feedback] Remove Deprecation Issue in Numpy

lectures/ak2.md, lectures/back_prop.md, lectures/finite_markov.md, lectures/likelihood_bayes.md, lectures/linear_models.md, lectures/lln_clt.md, lectures/mix_model.md, lectures/multivariate_normal.md, lectures/navy_captain.md, lectures/util_rand_resp.md, lectures/wald_friedman.md, lectures/wealth_dynamics.md
This PR fixes a syntax warning across the lecture series
@HumphreyYang if you have time would you mind review this PR to make sure an `r` shouldn't be an `rf` for example. It would be nice to have a double check of it.
=> FIX: syntax for strings python>=3.12

.github/workflows/cache.yml, .github/workflows/ci.yml, .github/workflows/publish.yml, lectures/kesten_processes.md
This PR updates our docker container to use the latest `cuda=12.8.1`
Includes a fix for `kesten_processes` use of `yfinance`
**Note:** this is currently defaulting to `cuda=12.4` as per the in-lecture `jax` backend so will work to resolve this.
=> MAINT: update docker environment

.github/workflows/cache.yml, .github/workflows/ci.yml, .github/workflows/collab.yml, .github/workflows/publish.yml, scripts/test-jax-install.py
This PR migrates GitHub Actions to use the new RunsOn service. 
The change are:
Due to conflicts between `torch` and `jax` software, we are installing the nightly `torch` stack (thanks @HumphreyYang) this is working well with CUDA=12.9 and doesn't downgrade CUDANN below 9.8 which is required by JAX.
=> ENH: enable RunsOn with custom ami

.github/workflows/ci.yml, lectures/troubleshooting.md
This PR is a minor update to the build env
=> MAINT: add pyro-ppl to build env

.github/workflows/ci.yml, .github/workflows/collab.yml, environment.yml, lectures/_admonition/gpu.md, lectures/ar1_bayes.md, lectures/back_prop.md, lectures/bayes_nonconj.md, lectures/mix_model.md
This PR addresses #452
~~This PR currently breaks `collab` testing. While google `collab` has `jax` it doesn't have a few other packages related to GPU such as `pyro` which is causing 1-2 lectures to fail. The installs will be listed at the top of the lecture, however a user will need to run that cell to install those packages for it to work.~~ 🤔 
I have switched these back on for local execution (this should fix `collab` while not upgrading the software for the other actions). I have documented this complexity and issue in #454 so doesn't need to be fixed here.
=> MAINT: remove jax, pyro, torch, and gpu related software installs + GPU admonition

lectures/prob_matrix.md
This PR updates the descriptions in `prob_matrix`.
=> [prob_matrix] Minor Updates

lectures/aiyagari.md
=> [aiyagari] MAINT: transfer np.sum(a * b) to a @ b

environment.yml, lectures/cass_koopmans_1.md
=> [cass_koopmans_1] Exercise Experimenting multiple $K_0$ values

lectures/mccall_model.md
Replace `np.sum(a * b)` with `a @ b`
#463
=> [mccall_model] Replace `np.sum(a * b)` with `a @ b`

lectures/kalman_2.md
Remove redundant ax.axhline call outside the simulation loop.
- The true effort level (u_0) lines are already plotted inside the simulate_workers function.
- The external ax.axhline call used u_0, which was undefined outside the loop.
- This cleanup avoids redundant code and potential NameError.
=> [kalman_2] Remove redundant axhline plotting

lectures/kalman_2.md
This PR refactors the `simulate_workers` function to follow Python best practices and enhance readability. The main changes include:
- Replaced `isinstance(..., type(None))` with `is None` checks for clarity.
- Avoided unnecessary equality checks like `diff == True` in favor of direct boolean evaluation.
- Used `is None` instead of `== None` for `None` comparisons.
- Replaced unnecessary list unpacking like `[y_hat_t[i]] = worker.G @ x_hat` with scalar extraction using `.item()`.  
The matrix multiplication returns a single-element array, so using `.item()` explicitly converts it to a scalar value, improving code clarity and avoiding the need for list unpacking.
=> [kalman_2] Refactor simulate_workers for PEP8 compliance and code clarity

lectures/opt_transport.md
Replace np.sum(a * b) with np.vdot(a, b)
https://github.com/QuantEcon/lecture-python.myst/issues/463
=> [opt_transport] Replace np.sum(a * b) with np.vdot(a, b)

lectures/ge_arrow.md
Hello,
Thank you for creating and maintaining this excellent lecture note. It has been very helpful for my studies.
I noticed a potential inconsistency between the theoretical definition of the risk-free rate and its implementation in the RecurCompetitive class.
The Issue:
- In the "Markov Asset Prices" section, the price of a risk-free bond in state i is defined as $R_i⁻¹ = Σ_j Q_{ij}$. This corresponds to summing the Q matrix across its rows (axis=1 in NumPy).
- The current implementation in the risk_free_bond function uses np.sum(self.Q, 0), which sums across columns (axis=0).
The Fix:
This PR corrects the summation axis from 0 to 1 to align the code with the theoretical text.
Please let me know if I have misunderstood anything.
=> [ge_arrow] Correct summation axis

lectures/likelihood_bayes.md, lectures/likelihood_ratio_process.md, lectures/mix_model.md, lectures/wald_friedman.md
This PR includes improvements Tom made to the lectures on likelihood ratio processes.
This PR addresses #500 and fix a major bug in `mix_model`.
=> [likelihood_bayes, mix_model] Lecture Improvements and Error Fixes

lectures/cass_koopmans_2.md, lectures/coleman_policy_iter.md, lectures/exchangeable.md, lectures/jv.md, lectures/lake_model.md, lectures/lqcontrol.md, lectures/multivariate_normal.md, lectures/svd_intro.md, lectures/von_neumann_model.md
This PR removes `SyntaxWarning` that appears after the cache rebuild.
=> [FIX] Remove Syntax Warning from Cache Rebuild

lectures/_static/quant-econ.bib, lectures/wald_friedman.md, lectures/wald_friedman_2.md
This PR fixes typos in the two `wald_friedman` lectures.
=> [wald_friedman] Fix minor typos across two wald_friedman lectures

lectures/von_neumann_model.md
Key changes
- Set the max-height of cells to none at the beginning
- Removed `object` after `class Nuemann`
- Adopted `sphinx-proof` environments
Question
- As I used the `sphinx-proof`, assumptions numbered as "I, II"  have been changed to "1, 2". But in the definition of `class Neumann`, some variables are named as `AI` and `AII`. Should I change the names of these variables to `A1` and `A2`? @mmcky
For example,
```
def __init__(self, A, B):
self.A, self.B = list(map(self.convert, (A, B)))
self.m, self.n = self.A.shape
assert self.A.shape == self.B.shape, 'The input and output matrices \
must have the same dimensions!'
assert (self.A >= 0).all() and (self.B >= 0).all(), 'The input and \
output matrices must have only non-negative entries!'
if (np.sum(B, 0) <= 0).any():
self.AI = False …
```
=> [von_neumann_model] lecture improvements

.github/workflows/ci.yml, lectures/_config.yml, lectures/back_prop.md, lectures/status.md
This PR fixes the `os.fork` warning documented in #548.
This together with #556, fixes #548.
=> [FIX] Fix jax and os.fork warnings

.github/workflows/linkcheck.yml, lectures/_static/quant-econ.bib, lectures/likelihood_ratio_process_2.md
This PR adds new exercises for B-E model with Bayes learning.
=> [likelihood_ratio_processes_2] Update new exercises with learning agents
